export const data = [
  {
    name: "Knit Cardigan and Dress",
    price: "110",
    currency: "USD",
    symbol: "$",
    img: "/knit_cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "Blue Plaid Blouse",
    price: "56",
    currency: "USD",
    symbol: "$",
    img: "/blue-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "Striped Top and Pants",
    price: "109",
    currency: "USD",
    symbol: "$",
    img: "/striped_top_pants.webp",
    orderQuantity: 1,
  },
  {
    name: "Floral Embroidered Jeans",
    price: "68",
    currency: "USD",
    symbol: "$",
    img: "/floral-jeans.webp",
    orderQuantity: 1,
  },
  {
    name: "Petal Collar Shirt and Knit Vest",
    price: "100",
    currency: "USD",
    symbol: "$",
    img: "/petal-collar-shirt.webp",
    orderQuantity: 1,
  },
  {
    name: "Striped Drawstring Waist Blouse",
    price: "66",
    currency: "USD",
    symbol: "$",
    img: "/striped-drawstring-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "Cropped Cardigan",
    price: "47",
    currency: "USD",
    symbol: "$",
    img: "/cropped-cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "Vibrant Striped Top",
    price: "44",
    currency: "USD",
    symbol: "$",
    img: "/vibrant-striped-top.webp",
    orderQuantity: 1,
  },
  {
    name: "long sleeve knit dress",
    price: "82",
    currency: "USD",
    symbol: "$",
    img: "/long-sleeve-knit.webp",
    orderQuantity: 1,
  },
  {
    name: "V-neck Puff Sleeves Dress",
    price: "84",
    currency: "USD",
    symbol: "$",
    img: "/v-neck-puff-sleeve.webp",
    orderQuantity: 1,
  },
  {
    name: "Cardigan and Floral Dress",
    price: "113",
    currency: "USD",
    symbol: "$",
    img: "/cardigan-floral.webp",
    orderQuantity: 1,
  },
  {
    name: "Cropped Cardigan Dress",
    price: "101",
    currency: "USD",
    symbol: "$",
    img: "/cropped-cardigan-dress.webp",
    orderQuantity: 1,
  },
  {
    name: "Cardigan and Cami",
    price: "78",
    currency: "USD",
    symbol: "$",
    img: "/cardigan-cami.webp",
    orderQuantity: 1,
  },
  {
    name: "Layered Look Top",
    price: "41",
    currency: "USD",
    symbol: "$",
    img: "/layered-look-top.webp",
    orderQuantity: 1,
  },
  {
    name: "Knit Tank Top",
    price: "45",
    currency: "USD",
    symbol: "$",
    img: "/knit-tank-top.webp",
    orderQuantity: 1,
  },
  {
    name: "Relaxed Fit Blouse",
    price: "62",
    currency: "USD",
    symbol: "$",
    img: "/relaxed-fit-blouse.webp",
    orderQuantity: 1,
  },
];

export const koreaData = [
  {
    name: "니트 카디건과 드레스",
    price: "153509.40",
    currency: "KRW",
    symbol: "₩",
    img: "/knit_cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "블루 플레드 블라우스",
    price: "78150.24",
    currency: "KRW",
    symbol: "₩",
    img: "/blue-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "줄무늬 상의와 바지",
    price: "152113.86",
    currency: "KRW",
    symbol: "₩",
    img: "/striped_top_pants.webp",
    orderQuantity: 1,
  },
  {
    name: "꽃 자수 청바지",
    price: "94896.72",
    currency: "KRW",
    symbol: "₩",
    img: "/floral-jeans.webp",
    orderQuantity: 1,
  },
  {
    name: "페탈 칼라 셔츠와 니트 조끼",
    price: "139554.00",
    currency: "KRW",
    symbol: "₩",
    img: "/petal-collar-shirt.webp",
    orderQuantity: 1,
  },
  {
    name: "스트라이프 드로스트링 허리 블라우스",
    price: "92105.64",
    currency: "KRW",
    symbol: "₩",
    img: "/striped-drawstring-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "크롭 카디건",
    price: "65590.38",
    currency: "KRW",
    symbol: "₩",
    img: "/cropped-cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "생동감 넘치는 스트라이프 탑",
    price: "61403.76",
    currency: "KRW",
    symbol: "₩",
    img: "/vibrant-striped-top.webp",
    orderQuantity: 1,
  },
  {
    name: "롱 슬리브 니트 드레스",
    price: "114,054",
    currency: "KRW",
    symbol: "₩",
    img: "/long-sleeve-knit.webp",
    orderQuantity: 1,
  },
  {
    name: "V넥 퍼프 슬리브 드레스",
    price: "117278.28",
    currency: "KRW",
    symbol: "₩",
    img: "/v-neck-puff-sleeve.webp",
    orderQuantity: 1,
  },
  {
    name: "카디건과 플로럴 드레스",
    price: "157767.21",
    currency: "KRW",
    symbol: "₩",
    img: "/cardigan-floral.webp",
    orderQuantity: 1,
  },
  {
    name: "크롭 카디건 드레스",
    price: "141013.17",
    currency: "KRW",
    symbol: "₩",
    img: "/cropped-cardigan-dress.webp",
    orderQuantity: 1,
  },
  {
    name: "카디건과 캐미",
    price: "108901.26",
    currency: "KRW",
    symbol: "₩",
    img: "/cardigan-cami.webp",
    orderQuantity: 1,
  },
  {
    name: "레이어드 룩 탑",
    price: "57242.97",
    currency: "KRW",
    symbol: "₩",
    img: "/layered-look-top.webp",
    orderQuantity: 1,
  },
  {
    name: "니트 탱크탑",
    price: "62827.65",
    currency: "KRW",
    symbol: "₩",
    img: "/knit-tank-top.webp",
    orderQuantity: 1,
  },
  {
    name: "릴렉스 핏 블라우스",
    price: "86562.54",
    currency: "KRW",
    symbol: "₩",
    img: "/relaxed-fit-blouse.webp",
    orderQuantity: 1,
  },
];
