export const data = [
  {
    name: "Knit Cardigan and Dress",
    price: "110",
    currency: "USD",
    symbol: "$",
    img: "/knit_cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "Blue Plaid Blouse",
    price: "56",
    currency: "USD",
    symbol: "$",
    img: "/blue-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "Striped Top and Pants",
    price: "109",
    currency: "USD",
    symbol: "$",
    img: "/striped_top_pants.webp",
    orderQuantity: 1,
  },
  {
    name: "Floral Embroidered Jeans",
    price: "68",
    currency: "USD",
    symbol: "$",
    img: "/floral-jeans.webp",
    orderQuantity: 1,
  },
  {
    name: "Petal Collar Shirt and Knit Vest",
    price: "100",
    currency: "USD",
    symbol: "$",
    img: "/petal-collar-shirt.webp",
    orderQuantity: 1,
  },
  {
    name: "Striped Drawstring Waist Blouse",
    price: "66",
    currency: "USD",
    symbol: "$",
    img: "/striped-drawstring-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "Cropped Cardigan",
    price: "47",
    currency: "USD",
    symbol: "$",
    img: "/cropped-cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "Vibrant Striped Top",
    price: "44",
    currency: "USD",
    symbol: "$",
    img: "/vibrant-striped-top.webp",
    orderQuantity: 1,
  },
];

export const koreaData = [
  {
    name: "니트 카디건과 드레스",
    price: "153509.40",
    currency: "KRW",
    symbol: "₩",
    img: "/knit_cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "블루 플레드 블라우스",
    price: "78150.24",
    currency: "KRW",
    symbol: "₩",
    img: "/blue-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "줄무늬 상의와 바지",
    price: "152113.86",
    currency: "KRW",
    symbol: "₩",
    img: "/striped_top_pants.webp",
    orderQuantity: 1,
  },
  {
    name: "꽃 자수 청바지",
    price: "94896.72",
    currency: "KRW",
    symbol: "₩",
    img: "/floral-jeans.webp",
    orderQuantity: 1,
  },
  {
    name: "페탈 칼라 셔츠와 니트 조끼",
    price: "139554.00",
    currency: "KRW",
    symbol: "₩",
    img: "/petal-collar-shirt.webp",
    orderQuantity: 1,
  },
  {
    name: "스트라이프 드로스트링 허리 블라우스",
    price: "92105.64",
    currency: "KRW",
    symbol: "₩",
    img: "/striped-drawstring-blouse.webp",
    orderQuantity: 1,
  },
  {
    name: "크롭 카디건",
    price: "65590.38",
    currency: "KRW",
    symbol: "₩",
    img: "/cropped-cardigan.webp",
    orderQuantity: 1,
  },
  {
    name: "생동감 넘치는 스트라이프 탑",
    price: "61403.76",
    currency: "KRW",
    symbol: "₩",
    img: "/vibrant-striped-top.webp",
    orderQuantity: 1,
  },
];
